config/routes.rb
OfficeToRent::Application.routes.draw do
  resources :people

  resources :instances

  resources :users

end

app/models/instance.rb
class Instance < ActiveRecord::Base
  attr_accessible :name, :url_token
end

app/models/person.rb
# This is the protected resource that shouldn't leak between DB instances
class Person < ActiveRecord::Base
  attr_accessible :name, :email
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password_hash, :salt, :instance_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  def index
    @instances = Instance.all
  end

  def show
    @instance = Instance.find(params[:id])
  end

  def new
    @instance = Instance.new
  end

  def create
    @instance = Instance.new(params[:instance])
    if @instance.save
      redirect_to @instance, :notice => "Successfully created instance."
    else
      render :action => 'new'
    end
  end

  def edit
    @instance = Instance.find(params[:id])
  end

  def update
    @instance = Instance.find(params[:id])
    if @instance.update_attributes(params[:instance])
      redirect_to @instance, :notice  => "Successfully updated instance."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @instance = Instance.find(params[:id])
    @instance.destroy
    redirect_to instances_url, :notice => "Successfully destroyed instance."
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(params[:person])
    if @person.save
      redirect_to @person, :notice => "Successfully created person."
    else
      render :action => 'new'
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update_attributes(params[:person])
      redirect_to @person, :notice  => "Successfully updated person."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to people_url, :notice => "Successfully destroyed person."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user, :notice => "Successfully created user."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user, :notice  => "Successfully updated user."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, :notice => "Successfully destroyed user."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/instances_helper.rb
module InstancesHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/instances/_form.html.erb
<%= form_for @instance do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :url_token %><br />
    <%= f.text_field :url_token %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/instances/edit.html.erb
<% title "Edit Instance" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @instance %> |
  <%= link_to "View All", instances_path %>
</p>

app/views/instances/index.html.erb
<% title "Instances" %>

<table>
  <tr>
    <th>Name</th>
    <th>Url Token</th>
  </tr>
  <% for instance in @instances %>
    <tr>
      <td><%= instance.name %></td>
      <td><%= instance.url_token %></td>
      <td><%= link_to "Show", instance %></td>
      <td><%= link_to "Edit", edit_instance_path(instance) %></td>
      <td><%= link_to "Destroy", instance, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Instance", new_instance_path %></p>

app/views/instances/new.html.erb
<% title "New Instance" %>

<%= render 'form' %>

<p><%= link_to "Back to List", instances_path %></p>

app/views/instances/show.html.erb
<% title "Instance" %>

<p>
  <strong>Name:</strong>
  <%= @instance.name %>
</p>
<p>
  <strong>Url Token:</strong>
  <%= @instance.url_token %>
</p>

<p>
  <%= link_to "Edit", edit_instance_path(@instance) %> |
  <%= link_to "Destroy", @instance, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", instances_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_for @person do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/people/edit.html.erb
<% title "Edit Person" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @person %> |
  <%= link_to "View All", people_path %>
</p>

app/views/people/index.html.erb
<% title "People" %>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
  </tr>
  <% for person in @people %>
    <tr>
      <td><%= person.name %></td>
      <td><%= person.email %></td>
      <td><%= link_to "Show", person %></td>
      <td><%= link_to "Edit", edit_person_path(person) %></td>
      <td><%= link_to "Destroy", person, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Person", new_person_path %></p>

app/views/people/new.html.erb
<% title "New Person" %>

<%= render 'form' %>

<p><%= link_to "Back to List", people_path %></p>

app/views/people/show.html.erb
<% title "Person" %>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<p>
  <%= link_to "Edit", edit_person_path(@person) %> |
  <%= link_to "Destroy", @person, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", people_path %>
</p>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :password_hash %><br />
    <%= f.text_field :password_hash %>
  </p>
  <p>
    <%= f.label :salt %><br />
    <%= f.text_field :salt %>
  </p>
  <p>
    <%= f.label :instance_id %><br />
    <%= f.text_field :instance_id %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/users/edit.html.erb
<% title "Edit User" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @user %> |
  <%= link_to "View All", users_path %>
</p>

app/views/users/index.html.erb
<% title "Users" %>

<table>
  <tr>
    <th>Name</th>
    <th>Password Hash</th>
    <th>Salt</th>
    <th>Instance</th>
  </tr>
  <% for user in @users %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.password_hash %></td>
      <td><%= user.salt %></td>
      <td><%= user.instance_id %></td>
      <td><%= link_to "Show", user %></td>
      <td><%= link_to "Edit", edit_user_path(user) %></td>
      <td><%= link_to "Destroy", user, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New User", new_user_path %></p>

app/views/users/new.html.erb
<% title "New User" %>

<%= render 'form' %>

<p><%= link_to "Back to List", users_path %></p>

app/views/users/show.html.erb
<% title "User" %>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Password Hash:</strong>
  <%= @user.password_hash %>
</p>
<p>
  <strong>Salt:</strong>
  <%= @user.salt %>
</p>
<p>
  <strong>Instance:</strong>
  <%= @user.instance_id %>
</p>

<p>
  <%= link_to "Edit", edit_user_path(@user) %> |
  <%= link_to "Destroy", @user, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", users_path %>
</p>